spring:
  application:
    name: seq
  mongodb:
    uri: ${MONGO_DB_URI}
    representation:
      uuid: standard
app:
  cors:
    allowed:
      - https://*.sequesterapp.com
      - https://sequesterapp.com